### PR TITLE
[N05] Lack of outcome validation 

### PR DESCRIPTION
**Pull request by yorhodes**
### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes https://github.com/celo-org/celo-labs/issues/612

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Comment by aaronmgdr** [comment]
I notice that there have been lots of PRs that haven't filled out the template. Whats the reason for that? Especially as this is an Open source project it seems important that each PR explains what it is for. even if it only fills out a part of the template and removes the rest. 

Also is master the right base for this PR?

**Comment by yorhodes** [comment]
> I notice that there have been lots of PRs that haven't filled out the template. Whats the reason for that? Especially as this is an Open source project it seems important that each PR explains what it is for. even if it only fills out a part of the template and removes the rest.
> 
> Also is master the right base for this PR?

master is the wrong base, thanks
I will make an effort to fill out the templates in the future, though some of these changes contain potentially sensitive information from the smart contract audit
hence the link to the clabs repo issues

**Review by m-chrzan — APPROVED** [review]
I think it's fine to include this just for completeness, although it's worth noting that these functions only ever return `true` if they return anything - they revert on a `require` otherwise.

**Comment by yorhodes** [comment]
> I think it's fine to include this just for completeness, although it's worth noting that these functions only ever return `true` if they return anything - they revert on a `require` otherwise.

The specific revert messages are nice I think

**Pull request merged**
