### PR TITLE
[Validator Badge] DSRV CeloWhale.com 0xF83C93ea360B66DDCD532960304948…

### PR DESCRIPTION
**Pull request by hqueue**
### Description

Add a validator group [DSRV CeloWhale.com](https://explorer.celo.org/address/0xf83c93ea360b66ddcd532960304948b1c10786a1/celo) to the Master Validator [Badge ID 003] markdown file.

During the stake-off, name of this group was "dsrv labs - WellDoneStake.com" and the group passed security audit.

### Other changes

N/A

### Tested

No code change.

### Related issues

N/A

### Backwards compatibility

No code change.

### CODE REVIEW

**Comment by henry-zhang-bohan** [comment]
Hey @hqueue 

As this [Forum post](https://forum.celo.org/t/the-great-celo-stake-off-the-details/136) outlines, “entities who obtain equal to or above 80 points qualify for the Master Validator seal”. Based on our records, your security audit score was 75, which is below the 80-point requirement. As such, your group was not awarded the “Master Validator” badge.

**Comment by hqueue** [comment]
Hey @bohan-zhang 

We got 95 points (with 10 bonus points) from the audit.
Even without bonus points, we got 85 points. Can you please take a look at it again?

**Comment by henry-zhang-bohan** [comment]
Yes indeed @hqueue -- apologies! approved

**Review by henry-zhang-bohan — APPROVED** [review]

**Comment by hqueue** [comment]
@bohan-zhang I've resolved conflicts by updating the PR. PTAL.

**Pull request merged**
