### PR TITLE
[L15] Stable token may not be backed up in the reserve

### PR DESCRIPTION
**Pull request by yorhodes**
### Description

See explanation in linked issue.

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Closed by discussion in https://github.com/celo-org/celo-labs/issues/598

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Comment by aaronmgdr** [comment]
all the changes to reserve-site and web package look like ones that we recently made, maybe some branching issue?

**Comment by yorhodes** [comment]
> all the changes to reserve-site and web package look like ones that we recently made, maybe some branching issue?

@aaronmgdr I am cherry picking your dependency fix onto an out of date branch because of our smart contract audit response strategy. See https://celo-org.slack.com/archives/CS7FCGQL8/p1598559493003200

**Comment by martinvol** [comment]
Left a comment in the issue: https://github.com/celo-org/celo-labs/issues/598#issuecomment-692361790

**Comment by yorhodes** [comment]
closing in favor of better documentation

**Pull request closed without merging**
