### PR TITLE
Release celocli 0.0.39 and bump version numbers

### PR DESCRIPTION
**Pull request by asaj**
## Description

This PR increments the versions of the CLI and contractkit packages after publishing to NPM.

## Other changes

None
## Tested

None
## Related issues

None
## Backwards compatibility

None
## Commit Message
_If using automerge, specify desired commit title_

_And desired commit message body_

### CODE REVIEW

**Comment by jmrossy** [comment]
Should https://github.com/celo-org/celo-monorepo/pull/3390 be closed then?

**Review by jmrossy — APPROVED** [review]
Lgtm

**Comment by asaj** [comment]
> Should #3390 be closed then?

Probably, will close now

**Comment by asaj** [comment]
Closing in favor of https://github.com/celo-org/celo-monorepo/pull/3408

**Pull request closed without merging**
