### PR TITLE
Remove consistently failing integration sync test

### PR DESCRIPTION
**Pull request by asaj**
### Description

Removes an end-to-end test that we no longer rely on. This test fails consistently which habituates us to failing master builds, which can hide underlying real issues.

### Tested

These are tests

### Other changes

None

### CODE REVIEW

**Review by nambrot — APPROVED** [review]
Ironically, the test is still failing?

**Comment by nategraf** [comment]
So I actually know why this test is failing (the `alfrajoresstaging` environment was deployed with a different epoch size than exists in the `.env.alfajorestaging` file at master) at the moment and am working on a fix. If I do fix it, would it be worth reinstating or has it been historically unreliable?

**Comment by nategraf** [comment]
I've created https://github.com/celo-org/celo-monorepo/pull/1504 to address the standing issue with this test if we want to keep it.

**Comment by nategraf** [comment]
We decided to go with #1504 to fix the test rather than nixing it.

**Pull request closed without merging**
