### PR TITLE
allow AzureKeyVaultClient to take in custom credential

### PR DESCRIPTION
**Pull request by zviadm**
### Description

Allow creating AzureKeyVaultClient with custom credentials

### CODE REVIEW

**Comment by zviadm** [comment]
ping? i already have a local fork for myself, but i think this is useful change for everyone, since sometimes it is better to use EnvironmentCredentials instead of DefaultCredentials (when you dont want to have a fallback, otherwise you get really confusing error messages).

**Comment by barbaraliau** [comment]
@zviadm @codyborn is this PR still relevant?

**Comment by zviadm** [comment]
> @zviadm @codyborn is this PR still relevant?

i think it is still relevant and useful but up to you all if you want to pick it up or not. For my own use cases, as I mentioned, I have already made a fork anyways so I don't care if it gets merged or not.

**Review by AlexBHarley — APPROVED** [review]
I think this makes sense to merge. It's inline with what we do in the [AWS HSM client](https://github.com/celo-org/celo-monorepo/blob/master/packages/contractkit/src/wallets/aws-hsm-wallet.ts#L29)

**Review by codyborn — APPROVED** [review]
Apologies for the delay. I'm quite bad about checking Github notifications. Looks good!

**Pull request merged**
