### PR TITLE
Revert "Add new analytics (#5772)", but keep backups disabled

### PR DESCRIPTION
**Pull request by i1skn**
### Description

Reverts celo-org/celo-monorepo#5772, but keeps backups disabled. 

There has been some confusion around this revert. This PR https://github.com/celo-org/celo-monorepo/pull/5808 has been already merged to  [Valora 1.5.5release branch](https://github.com/celo-org/celo-monorepo/tree/release/wallet/1.5.0), but it was only partially merged to master as another PR here https://github.com/celo-org/celo-monorepo/pull/5807. 

So, I've created this PR to only have the remaining changes between https://github.com/celo-org/celo-monorepo/pull/5807 and https://github.com/celo-org/celo-monorepo/pull/5808.

### Backwards compatibility

Yes

### CODE REVIEW

**Review by jeanregisser — COMMENTED** [review]
Unless I'm missing something, it feels we shouldn't revert these, providing the release build don't hit the Dex limit issue of course.

Does the release build currently fails without this revert?

**Comment by i1skn** [comment]
@jeanregisser I've just tested a build from master and it builds fine... So, probably, you are right and we can drop this PR.

**Comment by jeanregisser** [comment]
We might still need this 😅  
There's now a runtime error (only in release builds) 

See https://github.com/celo-org/celo-monorepo/issues/5958

**Comment by i1skn** [comment]
@jeanregisser so, do you think we might still need it or https://github.com/celo-org/celo-monorepo/pull/5960 did the job and we can close this one without merging?

**Comment by jeanregisser** [comment]
Yes I think we can close this now given #5960 did the job.

**Pull request closed without merging**
