### PR TITLE
Update initial cUSD/cGLD exchange rate

### PR DESCRIPTION
**Pull request by yerdua**
### Description

So far, there's been a default, hard-coded value of 10 as the gold price in cUSD. This is used in the oracle report in migrations (see: 08_stabletoken.ts).
Even if this value is soon overwritten by a running oracle, or expired to let the oracle take over, we want to start this out at a value that is close to the simulated oracle values that are reported in testnets. In `baklava`, the simulated oracle values hover around 1.

### Tested

Had to fix a `contractkit` test. Hopefully nothing else relies on the rate being set to `10`.

### CODE REVIEW

**Review by tkporter — APPROVED** [review]
Thanks!

**Comment by asaj** [comment]
Why put this in the .env file rather than the migrations config?

**Comment by yerdua** [comment]
> Why put this in the .env file rather than the migrations config?

Is there a way to do that in an env-specific way? I didn't see an obvious way of accomplishing that without using envvars.

**Comment by asaj** [comment]
Why do we care to do this in an env specific way?

**Pull request closed without merging**
