### PR TITLE
Interfaces solidity version update

### LINKED ISSUE #10339: Fix Interfaces being incompatible with newer Solidity versions

### PR DESCRIPTION
**Pull request by pahor167**
### Description

This PR allows to use interfaces in solidity 0.5.13 and higher. 

I checked and it seems there are no forward breaking changes (between 0.5.13 - 0.8.0) that would affect any of our interfaces.

### Other changes

No other changes

### Tested

Unit tests

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/10339

### Backwards compatibility

Compatible

### Documentation

None

### CODE REVIEW

**Comment by martinvol** [comment]
Have you checked if this will produce changes in the bytecode and thus trigger our tooling to redeploy everything?

As the CI is not complaining that the versions should be updated it looks good, but just to double check.

**Review by martinvol — APPROVED** [review]

**Review by soloseng — APPROVED** [review]
🚀

**Comment by pahor167** [comment]
> Have you checked if this will produce changes in the bytecode and thus trigger our tooling to redeploy everything?
> 
> As the CI is not complaining that the versions should be updated it looks good, but just to double check.

Unfortunately it changes bytecode but I dont believe there is a way around it

**Comment by martinvol** [comment]
Then the CI should complain about version changes required right?

**Pull request merged**
