### PR TITLE
Add Support for CeloToken Name in Registry

### PR DESCRIPTION
**Pull request by soloseng**
### Description

Added support for CELO token in the registry and used it throughout the core contracts.

This is in support of the effort to rename Gold to CELO.

### Other changes

Made changes to the migrations so that the registry is updated properly.

### Tested

unit tested

### Related issues

- Fixes https://github.com/celo-org/celo-blockchain-planning/issues/351
- Fixes https://github.com/celo-org/celo-blockchain-planning/issues/352

### Backwards compatibility

Yes, as existing functions have not changed

### CODE REVIEW

**Review by pahor167 — APPROVED** [review]

**Comment by pahor167** [comment]
Do we also have a task to add it to proposal on alfajores & mainnet ?

**Comment by palango** [comment]
Out of curiosity and because I didn't look into the PR in much detail. The Celo token address will be queryable by both `GOLD_TOKEN_REGISTRY_ID` **and** `CELO_TOKEN_REGISTRY_ID` or just the latter?

**Comment by soloseng** [comment]
> The Celo token address will be queryable by both GOLD_TOKEN_REGISTRY_ID and CELO_TOKEN_REGISTRY_ID 

That is correct. This was done to preserve backwards compatibility in the registry.

**Comment by soloseng** [comment]
> Do we also have a task to add it to proposal on alfajores & mainnet ?

Tracking here: https://github.com/celo-org/celo-blockchain-planning/issues/360

**Pull request merged**
