### PR TITLE
Update Lock Gold Error Message "Not Account"

### PR DESCRIPTION
**Pull request by aaronmgdr**
### Description

When trying to lock celo many devs have ran into the reversion message "not account".  this is ambiguous. often it seems like a param is missing or something. 

### Backwards compatibility

i believe changes in error messages are not consider api changes

### CODE REVIEW

**Review by soloseng — APPROVED** [review]
🚀

**Comment by pahor167** [comment]
Can we also update Accounts.sol since there is also quite few errors such as "Not an account" ?

It will also be necessary to update getVersionNumber function

**Comment by aaronmgdr** [comment]
> Can we also update Accounts.sol since there is also quite few errors such as "Not an account" ?
> 
> It will also be necessary to update getVersionNumber function

yes will do!

**Comment by aaronmgdr** [comment]
@pahor167 I went and updated places where error message as just `Not an Account` or `Unknown Account` to be more specific often to the action being performed. 

let me know if this needs further changes.

**Review by montera82 — APPROVED** [review]
:shipit:

**Review by pahor167 — APPROVED** [review]

**Pull request merged**
