### PR TITLE
EventKit + Sidebar Fix

### PR DESCRIPTION
**Pull request by aaronmgdr**
### Description

Creates an EventKit like the BrandKit. 
  * use markdown files for content
  * refactor several files from BrandKit to be reused in EventKit 

### Other changes

switched the sidebar to use css sticky instead of interaction observer

#### new 
Screen Shot 2020-06-02 at 5 47 41 PM
Screen Shot 2020-06-02 at 5 47 57 PM
Screen Shot 2020-06-02 at 5 48 09 PM
Screen Shot 2020-06-02 at 5 48 17 PM
Screen Shot 2020-06-02 at 5 48 27 PM
Screen Shot 2020-06-02 at 5 49 07 PM
Screen Shot 2020-06-02 at 5 49 17 PM

### Related issues

- Fixes https://github.com/celo-org/celo-labs/issues/457
fixes https://github.com/celo-org/celo-labs/issues/456
fixes https://github.com/celo-org/celo-labs/issues/455
fixes https://github.com/celo-org/celo-labs/issues/460
fixes https://github.com/celo-org/celo-labs/issues/458
fixes https://github.com/celo-org/celo-labs/issues/459
fies https://github.com/celo-org/celo-monorepo/issues/3690

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### CODE REVIEW

**Comment by aaronmgdr** [comment]
my apologies for the size of this

**Comment by jmrossy** [comment]
> my apologies for the size of this

Yeah... I've had my share of large PRs but over 100 files is intense. Any chance we can break this up?

**Comment by aaronmgdr** [comment]
closing for now to breakup

**Comment by aaronmgdr** [comment]
starting here https://github.com/celo-org/celo-monorepo/pull/3971

**Pull request closed without merging**
