### PR TITLE
Update Docs for Datadirectory on Testnets

### PR DESCRIPTION
**Pull request by YazzyYaz**
Based on datadirectory issues in https://discord.com/channels/600834479145353243/601046166620078100/767968101530468382 in #validator channel and following discussions

### CODE REVIEW

**Comment by trianglesphere** [comment]
I think that we need to include the datadir flag for the baklava proxy as well (line 240 in running a validator on baklava).

**Review by jcortejoso — APPROVED** [review]
lgtm

**Comment by YazzyYaz** [comment]
@trianglesphere good call! just added it to the proxy line. Please let me know if it's good to go now.

**Comment by mcortesi** [comment]
added another one... pls check that everywhere we use `--baklava` we also use `--datadir`

**Pull request merged**
