### PR TITLE
feat(oracle config): add USDCBRL configs and pairs

### PR DESCRIPTION
**Pull request by ghost**
### Description

Here I add configs for USDCBRL. It's been tricky choosing pairs, since deviations are large and volumes are low as well as spread over quite a few exchanges and pairs. For Bitso and Novadax we don't have up to date data, but have to trust nothing really changed for the worse in the quality of the trading since they were added for CELOBRL. Nadiem got data from Mercado and I merged it with what I could find for other pairs on tradingview.com. 

The different data sources have different time stamps for the reported prices. I resampled everything from 1-minute data to 1 hour, leaving a time inaccuracy of around 15-20 seconds, which comes from Mercado timestamps. I think this is ok! 

I approached it this way: 
- First I took USDCUSD pairs and merged them with the BRL pairs of CELOBRL, since they already have a level of trust from previous analysis
- Then I searched for pairs where most of the volume is traded, mainly Binance and Bitget
- I duplicated and switched some pairs to account for the BinanceUS/Binance incompatibility. The US client would have 5 pairs with this configuration, and the non-US clients 7. 
- Since volume is quite spread across exchanges and pairs and Brazilian exchange pairs usually have low volume, I added more pairs for increased robustness. 
- Deviations from average are in [-0.008, 0.006], however I only got 3 months of data so the `maxPercentageDeviation: 0.01` as in USDCUSD and USDCEUR seems appropriate to me. 

Tasks to do: 
- [x] add Bitget exchange adapter to celo-oracle
- [x] test by running the oracle client locally

### Other changes

No

### Tested

Tested by running the oracle client locally, looks gooddd

### Related issues

- Fixes https://github.com/mento-protocol/mento-general/issues/164

### Backwards compatibility

fully

### Documentation

- Price, deviation, and volume analysis: https://colab.research.google.com/drive/19O983_kmnIvdDbpR1Fj0_ZVn3jkp3hI3#scrollTo=dbh293sy3ljC
- Data: https://drive.google.com/drive/folders/19__z2SDXAG0BeWbkXQ-7sDM4nuXrJUEl

### CODE REVIEW

**Comment by ghost** [comment]
@nvtaveras @sissnad I added the exchange adapter and tested everything locally. Looks good, ready for review now

**Review by ninabarbakadze — APPROVED** [review]
It looks good to me but I'll let @sissnad confirm

**Comment by sissnad** [comment]
I was running it local. I have noticed some websocket related errors. And whitebit b/a spread has been above the threshold a couple of times. Wondering why that is the case 🤔 
Here is my [log file](https://github.com/celo-org/celo-monorepo/files/10848999/local_run.log)

**Review by sissnad — APPROVED** [review]
Looks good to me!
For the exchange config I am thinking it might be worth having a larger spread parameter for the cBRL/USDC exchange compared to cUSD/USDC

**Comment by ghost** [comment]
> Looks good to me! For the exchange config I am thinking it might be worth having a larger spread parameter for the cBRL/USDC exchange compared to cUSD/USDC

Thanks. I would deploy it as it is and if alerts indicate big ask spread is a problem revisit it

**Comment by sissnad** [comment]
> > Looks good to me! For the exchange config I am thinking it might be worth having a larger spread parameter for the cBRL/USDC exchange compared to cUSD/USDC

Sorry for the misunderstanding. I meant the spread parameter of the exchanges and not the max spread parameter of the oracle clients

**Comment by ghost** [comment]
no worries, it was my misunderstanding. Do you mean this? https://github.com/mento-protocol/mento-deployment/blob/main/script/upgrades/MU01/governance/Config.sol#L241 to account for a bit more rate uncertainty risk?

**Pull request merged**
