### PR TITLE
Remove non-existant import

### PR DESCRIPTION
**Pull request by nambrot**
### Description

This issue exists on master, but would break any build that is trying to verify against release 2, and thus this small fix needs to make it into this release to allow for verification of the future release 3 to work.

It was fixed on master at https://github.com/celo-org/celo-monorepo/pull/5945

### CODE REVIEW

**Comment by eelanagaraj** [comment]
hey @nambrot is there a reason not to merge commits on master through fdf4f4a (includes the fix in #5945)? Will the release not be merged into master eventually, or is there just a plan to have one massive merge request later on? Fine in either case and can approve this, but wanted to clarify. Thanks!

**Comment by nambrot** [comment]
Hi @eelanagaraj thanks for your question.

This PR is against the release branch for Release 2 of the Celo Core Contracts. It will culminate in a commit that will get deployed on the public testnets and mainnet. For that reason, master is no longer relevant for this branch (as that would require another audit).

However, a future release 3 will then compare against release 2 and for the verification tooling to work, the released commit will need to be able to build, thus we need to duplicate the fix on this branch (even though this branch will get merged into master).

Does that answer your question?

**Comment by eelanagaraj** [comment]
thanks for the response, makes sense!

**Review by eelanagaraj — APPROVED** [review]

**Comment by nambrot** [comment]
Merging this into #6402 so that the CI checks can pass together

**Pull request merged**
