### PR TITLE
Minor change tx-comment-encryption

### PR DESCRIPTION
**Pull request by jeamick**
Does this is also expected ```128-bit128 bit```? (line 5 under the Overview Section)

### Description

By reading the documentation to understand more about encrypted payment channel I found some typo errors

### Tested

NaN

### Other changes

Does this is also expected ```128-bit128 bit```? (line 5 under the Overview Section)

### Related issues

NaN

### Backwards compatibility

NaN

### CODE REVIEW

**Comment by trianglesphere** [comment]
Thanks for flagging this, `key pairkeypair` should probably be `keypair` and `128-bit128 bit` should be `128 bit`. If you'd like, I'm happy to pick up fixing the last change.

**Comment by jeamick** [comment]
Sure @trianglesphere  no problem

**Comment by jeamick** [comment]
So I can close the pull request @trianglesphere  ?

**Review by trianglesphere — APPROVED** [review]

**Comment by trianglesphere** [comment]
@jeamick I've approved it and can merge it in.

**Comment by timmoreton** [comment]
Thanks @jeamick !

**Pull request merged**
