### PR TITLE
[Wallet] Fix revoke verification and add back dev settings for it

### PR DESCRIPTION
**Pull request by jmrossy**
### Description

Add missing tx send to the revoke saga and add back the old dev setting to trigger this.

### Tested

Revoked.

### Backwards compatibility

yes

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
Great! 👍

**Comment by Lss-Ankit** [comment]
Hi @jmrossy and @jeanregisser  can you please provide more details to verify this task. currently i am using play store internal build  v1.1.0 (1004294309) and test flight build v1.1.0(21).

**Comment by jmrossy** [comment]
@Lss-Ankit No need to verify this one, it's a dev-mode special setting

**Comment by Lss-Ankit** [comment]
@jmrossy okay thanks for the updates.

**Pull request merged**
