### PR TITLE
AWS Terraform: Separate testnet and mainnet configurations

### PR DESCRIPTION
**Pull request by bgeihsgt**
### Description

Create a `mainnet` folder within the AWS terraform scripts so we can cleanly separate "golden" terraform scripts from anything experimental on testnet. This is largely copying/pasting the testnet content and tweaking it to match the mainnet instructions.

Once this PR is merged, I have additional changes to the mainnet scripts I will submit as a separate PR.

### Tested

I have used the mainnet scripts to run my own infrastructure.

### Backwards compatibility

This should not impact backwards compatibility.

### CODE REVIEW

**Comment by bgeihsgt** [comment]
@tkporter @jcortejoso wanted to ping on this one. Do you think this is a good approach to split these up in this way?

**Review by jcortejoso — APPROVED** [review]
Sorry for the long wait. Looks great

**Comment by aaronmgdr** [comment]
merge?

**Comment by bgeihsgt** [comment]
Oops - I meant to close this PR. Closing.

**Comment by bgeihsgt** [comment]
Trevor and I decided that splitting this wasn't the right approach, where instead we'd rely on branches to define different versions. All of the latest functionality changes + more have been merged with this PR: https://github.com/celo-org/celo-monorepo/pull/4542

**Pull request closed without merging**
