### PR TITLE
Hoist dev dependencies

### LINKED ISSUE #702: Hoist devDependencies
### Expected Behavior

To reduce duplication among packages, version's mismatch. Several dev
dependencies can be moved to the root package.json.

This also secures only one version for those versions, something that
is not even certain when two packages have the same version string on
the `package.json` (as can be seen on this yarn.lock)

Deps to be moved:
 - typescript
 - ts-node
 - jest
 - ts-jest

### PR DESCRIPTION
**Pull request by mcortesi**
To reduce duplication among packages, version's mismatch. Several dev
dependencies can be moved to the root package.json.

This also secures only one version for those versions, something that
is not even certain when two packages have the same version string on
the package.json (as can be seen on this yarn.lock)

Moved dependencies:
 - typescript
 - ts-node
 - jest
 - ts-jest

Exceptions:
 - blockchain-api & notification-service are google app engine projects
 that are built on google cloud, using only dependencies on it's
 package.json. Thus, typescript needs to be defined there.

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Tested

`yarn build`, `yarn test` and ci

### Other changes

Remove jest.config from celotool (it doesn't uses jest)

### Related issues

- Fixes #702

### CODE REVIEW

**Review by nambrot — DISMISSED** [review]
Amazing, thanks for doing this!

**Comment by aaronmgdr** [comment]
isnt web hosted on google cloud engine too?

**Comment by mcortesi** [comment]
> isnt web hosted on google cloud engine too?

@aaronmgdr it is. Good catch. But, it seems we build locally, see the npm script:

```
"deploy": "yarn run kill-dev; yarn run build; yarn remove @celo/types @celo/typescript; gcloud app deploy $MANIFEST",
```

**Review by cmcewen — APPROVED** [review]
Nice! Would be great just to add a note in the readme about handling dev deps 😄

**Pull request merged**
