### PR TITLE
Standardize Baklava Oracles

### PR DESCRIPTION
**Pull request by nvtaveras**
### Description

Moving forward we will run 4 oracles per currency pair on Baklava (2 in the centralus cluster and 2 in westus2) to reduce costs and operational overhead. These 4 oracles will run alongside the additional oracles that are operated by external providers. This PR removes the additional addresses that are no longer needed (I already passed CGPs to remove them from the whitelisted addresses).

### Other changes

This PR also removes the CELOBTC Oracles which were no longer running in the clusters but were still around in the config (also passed a CGP to remove them from sortedOracles)

### Tested

The new config has been deployed for all pairs and all our addresses are reporting
CELO/USD
```
celocli oracle:reports StableToken
 Address                                    Rate               Timestamp
 ────────────────────────────────────────── ────────────────── ──────────
 0x02b1d1bEA682FCab4448C0820f5Db409CCE4f702 0.7265030224587206 1675203571
 0x4fC82eb437af4c4EdC9c061E8C53D9a62F4DA42c 0.7260596004527443 1675203711
 0xe90F891710f625f18eCBF1E02eFB4FD1AB236A10 0.7260252811859705 1675203606
 0x3B522230C454cA9720665d66e6335a72327291e8 0.7255253023083058 1675203676
 0x460b3f8D3C203363Bb65b1a18d89D4FFB6B0C981 0.7255208919935114 1675203641
```

CELO/EUR
```
celocli oracle:reports StableTokenEUR
 Address                                    Rate               Timestamp
 ────────────────────────────────────────── ────────────────── ──────────
 0x8c387B0801426593448Aa5AE5CDfeea88F4576c1 0.6691650547250465 1675203711
 0x21d66472604A931211379A32710D26AFA203D190 0.6683642662527572 1675203696
 0xc496d108C6781Fbc9967E48873Eac2eA14ca119a 0.6679108930123742 1675203676
 0x4Ab2B594f08403b6324Cb0B172e332d8a08f1d5a 0.6679108930123742 1675203661
 0x042aC21b9CDA6171881135884DE16CF6aCa78375 0.6679073180537218 1675203641
```

CELO/BRL
```
celocli oracle:reports StableTokenBRL
 Address                                    Rate               Timestamp
 ────────────────────────────────────────── ────────────────── ──────────
 0xe467003845BDCbef710192d86263716815aB39f6 3.7103102152752556 1675203721
 0x3eE0a85E7d8e9d06617986d40623B1493139C5aE 3.71027289493371   1675203691
 0x4B7f9e7e18230a271109f67b60a70Fb3B4d0268A 3.7102367198731354 1675203751
 0x86F9c87d13347E6041e75F3A18533E07d284c419 3.707861525552826  1675203661
```

USDC/USD
```
celocli oracle:reports 0xA1A8003936862E7a15092A91898D69fa8bCE290c
 Address                                    Rate               Timestamp
 ────────────────────────────────────────── ────────────────── ──────────
 0xB15833400aEcC72cB759D4E57A3A5a9C2963a5C5 0.9999612698934469 1675203721
 0x6A0e5D8A496FEB59464028250C88A08341EA0831 0.9999611295068227 1675203661
 0x97eF27Cf3cE65B2558161aeb1e3cfF8B5F71fd04 0.9999611284964821 1675203691
 0x559702D23983eb29BCf30F2487d477945C0dBC6a 0.9999611192024888 1675203751
```

### Related issues

- Fixes https://github.com/mento-protocol/mento-general/issues/130

### CODE REVIEW

**Comment by ghost** [comment]
Why are there 5 addresses for EUR and USD and 4 for BRL and USDC?

**Review by ghost — APPROVED** [review]
looks good to me 🥇

**Comment by nvtaveras** [comment]
> Why are there 5 addresses for EUR and USD and 4 for BRL and USDC?

in the config there are only the 4 addresses which we control, while in the CLI output there are also reports from the external providers addresses. The extra ones for EUR and USD are from DT

**Review by ninabarbakadze — APPROVED** [review]
lgtm 👍🏼 appreciate that you pasted celocli results under Tested

**Pull request merged**
