### PR TITLE
[Wallet] Update copy on the onboarding screens

### PR DESCRIPTION
**Pull request by etuleu**
### Description

Updated copy on the on boarding screens, as per Cal's new designs.
I am not sure how we handle translations yet, but I did place google translate strings for Spanish for now.

### Other changes

None.

### Tested

Manual.

### Related issues

None.

### Backwards compatibility

Yes.

### Screenshots

Simulator Screen Shot - iPhone 11 - 2020-11-03 at 13 03 55
Simulator Screen Shot - iPhone 11 - 2020-11-03 at 13 13 18
Simulator Screen Shot - iPhone 11 - 2020-11-03 at 13 04 02
Simulator Screen Shot - iPhone 11 - 2020-11-03 at 13 04 08

### CODE REVIEW

**Review by jeanregisser — APPROVED** [review]
LGTM 👍

**Comment by etuleu** [comment]
> LGTM +1

thanks for the review Jean! I am going to double check today with the valora-copy group chat to make sure this is the actual copy they need. I will also take some screenshots if the valora branding repo is working for me now.

**Comment by etuleu** [comment]
Simulator Screen Shot - iPhone 11 - 2020-11-03 at 13 03 55
Simulator Screen Shot - iPhone 11 - 2020-11-03 at 13 03 59
Simulator Screen Shot - iPhone 11 - 2020-11-03 at 13 04 02
Simulator Screen Shot - iPhone 11 - 2020-11-03 at 13 04 08

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser Verified task using latest Test flight build v1.4.0 (28) and Android play store (internal build) v1.4.0 (1004294317)
Devices Used: Google Pixel Xl (8.1) , iPhone 6+ (12.4.5)\

Scenarios:
- Verify user is able to see the "Valora is a new way to send and receive value worldwide" first walk-through screen when user install fresh app **Pass**
-  Verify user is able to see the "Send funds across borders" second walk-through screen should show when user  tap on next button on first walk-through screen **Pass**
-  Verify user is able to see the "Convenient, reliable,and secure. your phone is your wallet" Third walk-through screen is should show when user  tap on next button on second walk-through screen **Pass**
-  Verify user is able to see the "Share money with those you value" walk-through screen is should show when user  tap on  Get started on Third walk-through screen **Pass**

  **Can you please let us know if we need to verify any thing else in this task?**

**Pull request merged**
