### PR TITLE
[Validator Badge] PretoriaResearchLab.io 0xddaa60B6d803674bBc434F1C2B261CeB67C2fd7c

### PR DESCRIPTION
**Pull request by aaronmboyd**
Note - scored 80 in Master Validator challenge.Understanding was that >= 80 was acceptable for the Master Validator badge and worked specifically on a few final items in TGCSO to get this within time constraints.

### CODE REVIEW

**Comment by henry-zhang-bohan** [comment]
Hey @aaronmboyd,

As this [Forum post](https://forum.celo.org/t/the-great-celo-stake-off-the-details/136) outlines, “entities who obtain equal to or above 80 points qualify for the Master Validator seal”. Based on our records, your security audit score was 66.7, which is below the 80-point requirement. As such, your group was not awarded the “Master Validator” badge.

**Comment by aaronmboyd** [comment]
From the forum post you linked: https://forum.celo.org/t/the-great-celo-stake-off-the-details/136

> Your multiplier boost will be the number of points you earn, scaled to a number between 0 and 100

and

> Entities who obtain equal to or above 80 **points** qualify for the “Master Validator” seal. 

My score was 80 points (and I can send the email from Celo to show this). What you're referencing of 66.67 is the BTU multiplier, which is 80 points scaled between 0 and 100. From everything I've read, and all the work I put in at the time to specifically meet the requirement which was discussed at length in the forums, this should be fine for the Master Validator seal shouldn't it?

**Comment by henry-zhang-bohan** [comment]
Hey @aaronmboyd you're right! My apologies for mixing up the numbers!

**Review by henry-zhang-bohan — APPROVED** [review]

**Comment by aaronmboyd** [comment]
@bohan-zhang When will this and other PRs for missing badges be merged?

**Comment by aaronmboyd** [comment]
Hi, I've updated my PR from ages ago to include your recent merge. Could you please merge this also? It's been approved and discussed in this PR with @bohan-zhang but hasn't progressed.

**Comment by henry-zhang-bohan** [comment]
Moved content to this PR: https://github.com/celo-org/celo-monorepo/pull/4501

**Pull request closed without merging**
