### PR TITLE
Add plugins to CLI

### PR DESCRIPTION
**Pull request by nambrot**
### Description

This PR adds plugin functionality to the CLI to allow users to add plugins to their CLI instance. This allows core developers to segment functionality and dapp developers to provide plugins for their contracts to CLI users.

One thing we should discuss prior to merging whether this represents a security risk and the addition of plugins should likely come with much bigger warnings and confirmation

### CODE REVIEW

**Comment by medhakothari** [comment]
This LGTM, and I think would be super useful for external developers. I can't speak much towards the security aspect, but I agree that if people are adding 3rd party plug-ins, they should have more substantial warnings. cc: @eelanagaraj @barbaraliau for your thoughts.

**Comment by barbaraliau** [comment]
> This LGTM, and I think would be super useful for external developers. I can't speak much towards the security aspect, but I agree that if people are adding 3rd party plug-ins, they should have more substantial warnings. cc: @eelanagaraj @barbaraliau for your thoughts.

Yes definitely agree with this. Who would be the best to review as far as security aspects?

**Comment by nambrot** [comment]
Not sure, to be honest

**Comment by eelanagaraj** [comment]
agree with more/bolder warnings both within the CLI + relevant docs; maybe @mcortesi has thoughts on this?

**Comment by ewilz** [comment]
as a sidenote, I'm currently making a potential plugin to the celocli for rewards distribution functionality. One thing I wish I could have, is access to the BaseCommand class to reuse all the built-in gas/signature functionality we've written. I'm basically just rewriting it with less features at the moment. I hackily tried to import it after adding `@celo/celocli` as an npm package (lol), but it wasn't available to import.

**Comment by eelanagaraj** [comment]
@barbaraliau @medhak1 @aslawson PTAL -- main file of concern is `../plugin-warning.ts`. 1) Should we just eliminate asking to confirm the plugin installation (since we also require the @celo/ scope)? 2) If we want to keep it, would love thoughts on the message (I removed 3rd-party references since that won't be possible for the time-being).

**Review by aslawson — APPROVED** [review]
🚢

**Pull request merged**
