### PR TITLE
Publish blockscout deployment info to pubsub

### PR DESCRIPTION
**Pull request by rkachowski**
### Description

Sends info about blockscout deployment to a known pubsub topic for handling and posting to slack

### Other changes

* Add publish to pubsub functionality to `gcloud_utils`

### Tested

* Ran locally with `--helmdryrun` to assert functionality

### CODE REVIEW

**Comment by carterqw2** [comment]
Let's turn it into a post-upgrade hook similar to [other similar tasks](https://github.com/celo-org/celo-monorepo/pull/9140/commits/7a34040551b046accacc157084625bedde24570d)?

**Comment by rkachowski** [comment]
We can also do that in the helm PR, but until that's released we would need it in celotool to get any value. 

I'm not too sure how to go about accessing a pubsub topic from a helm hook - grafana looks like it bundles a shell script which calls out via a dedicated container, we'd have to do something similar with gcloud

**Review by jcortejoso — APPROVED** [review]
lgtm

**Comment by jcortejoso** [comment]
> We can also do that in the helm PR, but until that's released we would need it in celotool to get any value.
> 
> I'm not too sure how to go about accessing a pubsub topic from a helm hook - grafana looks like it bundles a shell script which calls out via a dedicated container, we'd have to do something similar with gcloud

I think from a helm hook container how it would look like:
Inside celotool:
1. Create a Service Account with using here.
2. Attach a policy/role allowing to publish in the PubSub topic.
3. Create the rolebinding to allow a Kubernetes Service account to impersonate this GCP SA ([workload identity tutorial](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity))

In the pod run by the Helm hook:
1. Run a container with a `gloud-sdk` image.
2. Container has assigned a K8s Service Account that was authorized in last section point 3.
3. The K8s service account has an annotation to indicate the GCP Service account to impersonate.
4. gcloud automatically get the credentials when a Service account is provided in this way.


It is a bit complex setup but I can help you setting up if you prefer that way.

**Comment by rkachowski** [comment]
Hey Javi, thanks for reviewing. We went with an approach that consumes GCP audit logs via cloud functions which has the benefit of working directly on the changes applied on the cluster rather than through the deployment mechanism

**Pull request closed without merging**
