### PR TITLE
Use blockchain master for e2e tests

### PR DESCRIPTION
**Pull request by palango**
### Description

Return to running the e2e tests against blockchain master.

### CODE REVIEW

**Comment by karlb** [comment]
Depending directly on master will cause problems with reproducibility. Alternatively, we could regularly update to the latest commit hash from celo-blockchain master. That would also allow us to include necessary fixes in the same PR as the commit hash update.

On the other hand, do we have the necessary discipline/process to frequently update the commit hash and check the results?

In any case, I am strongly in favour of having a more recent celo-blockchain dependency than the latest stable release!

**Comment by karlb** [comment]
Why don't the e2e test fail when https://github.com/celo-org/celo-monorepo/pull/10397 and https://github.com/celo-org/celo-monorepo/pull/10398 are not merged?

**Comment by palango** [comment]
> Why don't the e2e test fail when #10397 and #10398 are not merged?

Good question, I'm wondering about that as well.

**Comment by karlb** [comment]
I didn't find an explanation, yet. The test also succeeds locally and uses celo-blockchain's current master (e10394dfcaef2825ca799c97ddea3d3e78593724).

**Pull request closed without merging**
