### PR TITLE
Fix celotool dockerfile

### PR DESCRIPTION
**Pull request by tkporter**
### Description

Adds `contractkit` & `protocol` dependencies to the celotool dockerfile. Otherwise builds would fail, because `contractkit` is required (and `contractkit` has `protocol` as a dependency)

### Tested

Docker builds succeeded

### Other changes

n/a

### Related issues

n/a

### Backwards compatibility

Yes

### CODE REVIEW

**Comment by ashishb** [comment]
How big is the docker file now? Can you try `docker inspect` and report the new vs old results here?

**Comment by tkporter** [comment]
Looking at GCR "virtual size":
new: 677.2 MB
old: 548.4 MB

:(
Any ideas for reducing size?

**Review by mcortesi — APPROVED** [review]

**Comment by mcortesi** [comment]
> Looking at GCR "virtual size":
> new: 677.2 MB
> old: 548.4 MB
> 
> :(
> Any ideas for reducing size?

@ashishb this could be "fixed" if we used "npm builds" inspect of copying the mono repo... 
eg. use the contractkit deployed version.

**Comment by ashishb** [comment]
> Any ideas for reducing size?

Yes, do a multi-stage build - https://github.com/celo-org/celo-monorepo/blob/master/dockerfiles/cli/Dockerfile#L48

**Pull request merged**
