### PR TITLE
Add new Coinbase implicit pair for cEUR

### PR DESCRIPTION
**Pull request by nvtaveras**
### Description

This is essentially the same as https://github.com/celo-org/celo-monorepo/pull/9939 but it fixes a slight error in the configuration as the Coinbase pair is `USDTEUR` instead of `EURUSDT`. I can't push the changes on top of the old PR since it was created from @sissnad's fork.

This will be deployed together with https://github.com/celo-org/celo-oracle/pull/133

### CODE REVIEW

**Review by bowd — APPROVED** [review]

**Comment by bowd** [comment]
Looks good to me, but I've never configured this so I can't tell if there's anything subtle missing.
I also imagine that you need to update this PR with the new image hash after the oracles are built and added to the docker repo, right?

**Review by bowd — CHANGES_REQUESTED** [review]
Docker Image hash for new oracles build with https://github.com/celo-org/celo-oracle/pull/132/files merged.

**Comment by nvtaveras** [comment]
> Looks good to me, but I've never configured this so I can't tell if there's anything subtle missing. I also imagine that you need to update this PR with the new image hash after the oracles are built and added to the docker repo, right?

@bowd The main thing to look out for when adding new implicit pairs is that the pairs in the path are correctly inverted when needed and that we are not double counting volume by re-using CELOXXX pairs.  

In this case we are keeping all the previous pairs:

```
[{exchange: 'BITTREX', symbol: 'CELOEUR', toInvert: false}],
[{exchange: 'COINBASE', symbol: 'CELOEUR', toInvert: false}],
[
     {exchange: 'BINANCE', symbol: 'CELOUSDT', toInvert: false}, 
     {exchange: 'BINANCE', symbol: 'EURUSDT', toInvert: true}
]
```

and adding a new coinbase triplet:
```
[
     {exchange: 'COINBASE', symbol: 'CELOUSD', toInvert: false},
     {exchange: 'COINBASE', symbol: 'USDTUSD', toInvert: true},
     {exchange: 'COINBASE', symbol: 'USDTEUR', toInvert: false}
],
```

notice that the rate of the `USDT/USD` pair is inverted to go from `CELO/USD` to `CELO/USDT` and that we keep the USDT/EUR rate in the original form to go from `CELO/USDT` to `CELO/EUR`.

I also updated the .env files with the new `rc3` tag. It looks like the CI is still configured to push to the registry and it's failing, so I ran the script in the repo that pushes to the new container registry.

**Comment by bowd** [comment]
> @bowd The main thing to look out for when adding new implicit pairs is that the pairs in the path are correctly inverted when needed and that we are not double counting volume by re-using CELOXXX pairs.

Yup, that's the part I did get and verified myself when doing the review, but it's still relying on assumptions I'm making about how things are implemented under the hood.

**Review by bowd — APPROVED** [review]

**Pull request merged**
