### PR TITLE
expose lesserAndGreater functions from GovernanceWrapper

### PR DESCRIPTION
**Pull request by zviadm**
### Description

These lesserAndGreater* functions are quite useful if you want to interact with 
the Governance contract in more custom ways.
Make them public so they can be accessed outside of the module.

### Other changes

n/a

### Tested

testing with pull request.

### Related issues

n/a

### Backwards compatibility

n/a

### CODE REVIEW

**Review by eelanagaraj — APPROVED** [review]
LGTM
Edit: sorry for the change, see below. Thanks!!

**Review by eelanagaraj — CHANGES_REQUESTED** [review]
could you add docstrings to these functions now that they're public?

**Review by AlexBHarley — APPROVED** [review]

**Review by AlexBHarley — CHANGES_REQUESTED** [review]
Woops only just now saw request for comment

**Comment by zviadm** [comment]
I didn't end up using these functions directly, so just dropping the PR

**Pull request closed without merging**
