### PR TITLE
[Wallet] Upgrade react-native-sms-retriever to fix multiple SMS imports

### LINKED ISSUE #5657: Update dependency for @celo/react-native-sms-retriever
### Expected Behavior

We depend on the latest commit in master for https://github.com/celo-org/react-native-sms-retriever

### Current Behavior

We depend on the commit in `cmcewen/androidx` branch

Files to be updated:
* https://github.com/celo-org/celo-monorepo/blob/c6ebf0661f83434f7f1c4d20a6f6663fa45b97c4/packages/react-components/package.json#L17
* https://github.com/celo-org/celo-monorepo/blob/c6ebf0661f83434f7f1c4d20a6f6663fa45b97c4/packages/mobile/package.json#L45

### Blocked by

Ideally we want to update this when https://github.com/celo-org/celo-monorepo/issues/5209 is fixed.

### PR DESCRIPTION
**Pull request by i1skn**
### Description

Upgrading `react-native-sms-retriever` to avoid duplicating attestation codes when auto import SMSs on Android.

### Other changes

Update the issue link for the race-condition issue https://github.com/celo-org/celo-monorepo/issues/6262

### Tested

Android Device, verification flow

### Related issues

- Fixes https://github.com/celo-org/celo-monorepo/issues/5657 & https://github.com/celo-org/celo-monorepo/issues/5209

### Backwards compatibility

Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]

**Comment by Lss-Ankit** [comment]
Hi @etuleu @i1skn Verified issue with Android play store internal build v1.7.2 (1004294329) & test flight build v1.7.2 (39) and found the following : 
- User is able to verify their phone number by receiving 3 attestations code. 
- Verified that user is able to get the attestations code when user taps on Resend all, Resend two , and Resend last option while signing. 
- Verified that between two attestations ~5 second gaps. 
- Also we have observed that Minute counting is stopped and user is redirect to Enter three code fields if user has received all attestation code before completing 2 minutes. 

Please let us know if we need to verify any thing else? 
Devices: Google Pixel XL (8.1) , iPhone SE 2 (14.2) 
Thanks !!

**Comment by i1skn** [comment]
Thanks, @Lss-Ankit !!! If possible can you verify the following: after requesting 3 attestations immediately disable SIM card, so SMSs would not be auto imported. Then go back and forth to Enter Codes screen a couple of times and only then turn SIM card on again, so SMS can be auto imported and check that there are no duplicates. Thanks!

**Comment by Lss-Ankit** [comment]
Sure @i1skn  Will verify the above mentioned flow and get back to you with updates :)

**Comment by Lss-Ankit** [comment]
Hi @i1skn  I have checked below two scenarios using Android  internal build V1.7.2(1004294329) & Test Flight build V1.7.2(39).

**1st Scenarios: Back & forth** 
1. Tap on Start button. 
2. fil the captcha. 
3. Timer screen is shown. 
4. Disable the Sim. 
5. After two min user is on Enter three attestation screen. 
6. Tap on Back arrow. 
7. Tap on resume button and user is navigate to again to  Enter three attestation screen. 
8. Perform Step 7 2 more time. 
9. Enable the Sim 
10. Observed Got only 3 Attestation and that are auto imported and no duplicate attestation are recieved.

**2nd scenarios: Resend all messages**
1. Tap on Start button. 
2. fil the captcha. 
3. Timer screen is shown. 
4. Disable the Sim. 
5. After two min user is on Enter three attestation screen. 
6. Tap on Back arrow. 
7. Tap on resume button and user is navigate to again to  Enter three attestation screen. 
8. Perform Step 7 2 more time. 
9. Tap on Resend all message option. 
10. wait for 2 minutes. 
11. Enable the Sim 
10. Observed Got only 3 Attestation and that are auto imported and no duplicate attestation are received.


**Note:** 
- Got duplicate attestation 2 times when performing 2nd scenarios, however after that I have performed that scenarios 4 times but got only 3 attestation and did not get any duplicates. 
- Also, Sometime only 2 or 1 attestation code is received after enabling the Sim in both scenarios. however attestation is received after few minutes or tapping on Resend all/2 messages option. 
- We have performed scenarios using Indian phone sim card/number +91 code. 

Please let me know if i need to verify any things else.

**Pull request merged**
