### PR TITLE
Add GPG public key for or@clabs.co

### PR DESCRIPTION
**Pull request by oneeman**
### Description

Add my GPG public key (or@clabs.co) so that in the future I can sign celo-blockchain docker images.  Verification instructions are here: https://github.com/celo-org/celo-monorepo/blob/master/packages/web/openpgpkey/README.md

### CODE REVIEW

**Comment by trianglesphere** [comment]
Make sure that you add your name on the list of people that have added their keys in the docs

**Comment by oneeman** [comment]
@trianglesphere Thanks, I added it now and sorted that list alphabetically while I was at it.

**Comment by barbaraliau** [comment]
Will #6252 affect this? Iirc the `/web` directory is removed in that PR.

**Comment by oneeman** [comment]
Closing this since the website is being removed from the monorepo in favor of a separate repo (#6252).  Will open up a PR on that repo instead.

@trianglesphere The list of users who have been added is still in this repo (in the docs section), so a separate PR on this repo will still be needed, but I will do that once my key is on there.

And the instructions at https://github.com/celo-org/celo-monorepo/blob/master/developer_key_publishing.md will have to be updated as well, I can do that.

**Pull request closed without merging**
