### PR TITLE
Revert adding phone-utils to Attestations wrapper

### PR DESCRIPTION
**Pull request by isabellewei**
### Description

Including `phone-utils` as a dependency greatly increases the `contractkit` bundle size

### CODE REVIEW

**Review by alecps — APPROVED** [review]
Looks good! Remember that you need to remove it from package.json too 😉

**Comment by isabellewei** [comment]
> Looks good! Remember that you need to remove it from package.json too 😉

Seems like it's not a dependency in the package.json but just a devDependency, which @aaronmgdr added. I'll let him chime in about what the right thing to do is!

**Comment by aaronmgdr** [comment]
> > Looks good! Remember that you need to remove it from package.json too 😉
> 
> Seems like it's not a dependency in the package.json but just a devDependency, which @aaronmgdr added. I'll let him chime in about what the right thing to do is!

I added it at one point while moving things around and then thought I removed it, If you can remove it now that would be wonderful.

**Comment by aaronmgdr** [comment]
Thank you for this

**Review by aaronmgdr — APPROVED** [review]

**Comment by isabellewei** [comment]
Can't remove `phone-utils` from the `devDependencies` because it's being used in a test:https://github.com/celo-org/celo-monorepo/blob/1d73f149d2005a9c8894841776ae20ed19003925/packages/sdk/contractkit/src/wrappers/Attestations.test.ts#L2

**Comment by aaronmgdr** [comment]
phone utils used in a test so keep as devDep

**Pull request merged**
