### PR TITLE
[Wallet] Redesign Consumer Incentives screen

### LINKED ISSUE #6765: Valora 1.10 integration polish
### Expected Behavior

We rushed the integration with v1.8 and v1.9. As a consequence, some parts of the integration might not be the most user-friendly.

- Add visual to the rewards detail page to make it more user-friendly
- Fix layout issues
- Make it clearer to users how much to expect in rewards based on their balance
- Link to T&C at the bottom of the page (include more details in there as needed)
- Make it clearer that the reward is temporary even after the introductory period

### Current Behavior

What is the current behavior?

### PR DESCRIPTION
**Pull request by gnardini**
### Description

UI changes for the Consumer Incentives educational screen.
[See mockups on Figma](https://www.figma.com/file/31HUGhIHLXEm1qwVpHV1QR/Consumer-Incentives?node-id=831%3A10833)

### Other changes

N/A

### Tested

Manually:
Android (slightly old screenshot):
Simulator Screen Shot - iPhone 11 - 2021-02-02 at 03 13 57
iOS:
Simulator Screen Shot - iPhone 11 - 2021-02-02 at 21 01 07

### Related issues

- Fixes #6765

### Backwards compatibility

N/A

### CODE REVIEW

**Review by etuleu — APPROVED** [review]
Looks awesome!

**Review by jeanregisser — APPROVED** [review]
🚢 👍

**Comment by Lss-Ankit** [comment]
Hi @gnardini @isabellewei We have verified this task on latest android internal build 1.10.0(1004294335) & Testflight build 1.10.0(45) and observe the following.

**User without verified phone number**

- User not able to see the below options on Celo Rewards page 

1. Get $1 in celo per month with a minimum balance on 20 cUSD
2. Get $5 in celo per month with a minimum balance on 100 cUSD 
3. Get $10 in celo per month with a minimum balance on 500 cUSD
4. Not able to see Rewards kickoff 

**Attachment:** [UpdatedOptionsiSNotShown.jpg](https://drive.google.com/file/d/1NO2nG0Q9i7VNXyL4bbinBkDRibeP_dV1/view?usp=sharing)

**User without verified phone number**

- User is also not able to see the above points even user logged in with verified phone number 

**Note:** We dont have access for mockups on Figma, Can you give access to celoqa@lodestoneo.com.

**Comment by isabellewei** [comment]
@Lss-Ankit I've given you access to the Figma, and we've updated the text from Firebase so you should be able to see it now!

**Comment by Lss-Ankit** [comment]
Hi @isabellewei We have again verified this on latest builds Android internal build V1.10.1 & Testflight build V1.10.1(46) and observe the followings

- User is able to see the below options on Celo Rewards page
- Get $1 in celo per month with a minimum balance on 20 cUSD
- Get $5 in celo per month with a minimum balance on 100 cUSD
- Get $10 in celo per month with a minimum balance on 500 cUSD
-  able to see Rewards kickoff

**Note:** Not able to open Figma screens file Not found error message is shown.
[**Attachment:**](https://drive.google.com/file/d/1ZkUeTNWFwNUfWbO3HOxaXmfTbezE73hZ/view?usp=sharing)

Please let us know if we need to test anything else.
Thanks!

**Pull request merged**
