### PR TITLE
[Wallet] Add correct decimal separator on CELO Withdrawal

### LINKED ISSUE #1309: [Android] [Device Specific] User is unable to enter a decimal value in the “Amount” field on “Send or Request” screen while proceeding for “ Send or request “ payment.
**App version:** Play store build v1.5.0
**Repro on:**  Samsung s4 mini (4.4.2), Samsung Galaxy Grand prime (5.1.1), 
**Does not repro on:** Moto E (4.4.4), Samsung  Galaxy S4 (5.0), Samsung Galaxy A5 (6.0.1), Samsung Galaxy A5 (7.0).  
**Priority:** Medium 
**Testing Account:** (315) 678-6563/[Backup Kay](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit?usp=sharing)
 
**Repro Steps:** 
1) Launch the app. 
2) Tap on + tab. 
3) Tap on Celo contact user. 
4) Enter an amount and tap on “.” (Dot) button on the keypad. 
5) Observe 

**Impact:** User is blocked to send the dollar amount with cent while proceeding for payment. 
**Current Behavior:** User is unable to enter a decimal value in the “Amount” field
**Expected Behavior:** User should be able to enter a decimal value in the “Amount” field
**Attachment:** [Android_BlockedToSendDollarWithCent.mp4](https://drive.google.com/file/d/1m3BQcB9muKeJIYLV9U9Z9o_N5YaXhgPn/view?usp=sharing) (Bug observe at 14 sec)

### PR DESCRIPTION
**Pull request by gnardini**
### Description

When withdrawing CELO using an OS that uses commas as decimal separators instead of dots (for example, Argentinian) the decimal portion was being cut off. It's not anymore with this PR.

### Tested

Manually

### Related issues

- Fixes #1309

### CODE REVIEW

**Review by jeanregisser — CHANGES_REQUESTED** [review]
Awesome! Before merging this, could you update the unit test to cover this?

**Comment by gnardini** [comment]
@jeanregisser Thanks for looking out for the test coverage, it will definitely help avoid issues in the future 🙏

**Review by jeanregisser — APPROVED** [review]
Awesome! 💯

**Comment by Lss-Ankit** [comment]
Hi @gnardini Verified with task with using Android play store (internal build) v1.4.0 (1004294317) and found the following: 
- Dot or Comma is not shown when user is on CELO Buy/ Sell screen. 
Verified On device Samsung Galaxy A3(5.0.2) 
Attachment: 
CELO

**Pull request merged**
