### PR TITLE
[C01] Funds of the Escrow contract can be locked by anyone

### PR DESCRIPTION
**Pull request by mrsmkl**
### Related issues

- Fixes https://github.com/celo-org/celo-labs/issues/259

### CODE REVIEW

**Review by mcortesi — APPROVED** [review]
I would just ask @nambrot if payment is not something that can/should be repeated

**Comment by mrsmkl** [comment]
Ok. Looking from some code, the `paymentId` is randomly generated address. But perhaps it will be changed later on.

**Review by nategraf — APPROVED** [review]
Same comment as Mariano, but overall it looks good!

**Review by nambrot — APPROVED** [review]
Indeed, a payment ID should never be repeated

**Pull request merged**
