### PR TITLE
[Wallet] Allow up to 1% difference on exchange rate for exchanging CELO

### LINKED ISSUE #5279: Soften minBuyAmount restriction on CELO exchanges
### Expected Behavior
Users should be able to exchange without CELO for cUSD without having their transactions reverted due to shifts in the exchange rate.

### Current Behavior
When the exchange rate shifts too much in between exchange estimation and execution, the transaction is reverted. How we define "too much" is probably too aggressive given we've seen this error happen fairly frequently, it creates a confusing user experience to throw a failing error, and user expectations are probably closer to that of a market order than limit order.

https://celo-org.slack.com/archives/CL7BVQPHB/p1602003881149900?thread_ts=1601931476.130200&cid=CL7BVQPHB

https://celo-org.slack.com/archives/CE8KJ192M/p1602115985037800?thread_ts=1602072921.028900&cid=CE8KJ192M

https://sentry.io/organizations/celo/issues/1840948860/?project=1250733&query=is%3Aunresolved+Calculated+buyAmount+was+less+than+specified+minBuyAmount&statsPeriod=14d

### PR DESCRIPTION
**Pull request by gnardini**
### Description

Before this PR, if we wanted to buy X CELO we were accepting to receive at a minimum X-0.01. This caused several errors, especially with bigger numbers since the exchange rate can vary between the estimation and the execution of the request. This PR changes that to accept at least X*0.99 of the input amount.

### Tested

Adding a log for the limit and using different values to see that the minimum is 0.99 * the input amount.

### Related issues

- Fixes #5279

### CODE REVIEW

**Review by tarikbellamine — APPROVED** [review]
Nice!

**Comment by Lss-Ankit** [comment]
Hi @gnardini We have verified task using Test flight build v1.3.0(27) and Android play store internal build v1.3.0(1004294316) and found the following: 
- 0.010 cUSD (Exchange fee)  is cut when user buy 0.01 CELO. 
- 0.020 cUSD (Exchange fee) is cut when user buy 0.02 CELO
- 1.94 cUSD (Exchange fee) is cut when user buy 1 CELO. 

Also, we have observed that Exchange fee is shown 0 on Buy CELO screen. 
Attachment: 
CELO_Exchangefee

can you please confirm is it expected behavior or we need to file a bug for the same? 
Also, please let us know if we need to verify any thing else ? 
Thanks!

**Comment by gnardini** [comment]
Hi @Lss-Ankit 

This is a bit of a behind the scenes change. The only thing to verify is that the exchanges still go through successfully, the rest wasn't modified by this task.

Thanks for verifying!

**Comment by Lss-Ankit** [comment]
Okay thanks @gnardini  for  the update. 
And FYI, for exchange fee 0 we have bug https://github.com/celo-org/celo-monorepo/issues/2701

**Pull request merged**
