### PR TITLE
Docs: Fixing some terms

### PR DESCRIPTION
**Pull request by marceljay**
### Description
Mostly fixing some terms like the obsolete "Gold". 
I specifically tried to avoid changing Gold => CELO when it was in the context of a contract or the CLI docs.

In certain instances there was some ambiguity regarding the semantics, which is why I only put CELO in brackets:
> Check that the `ReleaseGold` contract address is associated with a registered Locked Gold (CELO) Account:

### Tested
Not required, only changes to markdown.

### CODE REVIEW

**Comment by critesjosh** [comment]
@YazzyYaz, adding you as a reviewer as you have good visibility into when would be a good time to make this update

**Comment by YazzyYaz** [comment]
@marceljay as specified in this ticket: https://github.com/celo-org/celo-monorepo/pull/7425 and this ticket: https://github.com/celo-org/celo-monorepo/pull/5536 a few changes need to made for a few open CLI tickets before we commit to a full rename in the docs. Also, contracts will still retain their name Gold in this case so we need to keep that in mind. Hopefully we can resolve the doc updates soon when the CLI tickets are completed.

**Comment by marceljay** [comment]
@YazzyYaz 
I have tried to avoid renaming anything related to the **contracts**, since they obviously won't be renamed. As far as I am concerned, my PR could be merged without any logical conflicts, as I only changed the parts not related to CLI or Code.

**Comment by marceljay** [comment]
Great.

**Comment by marceljay** [comment]
That was maybe an hour of work... sad :(

**Pull request closed without merging**
