### PR TITLE
[Validator Badge] Censusworks 0x0d4f8cEA48cDaDEAe345431577a64983c0535B12

### PR DESCRIPTION
**Pull request by jamescowling**
### Description

Add Censusworks group address as receiving master validator badge. Censusworks was known as Census during the stake-off and received the master validator certification.

### CODE REVIEW

**Comment by henry-zhang-bohan** [comment]
Hey @JamesCowling,

As this [Forum post](https://forum.celo.org/t/the-great-celo-stake-off-the-details/136) outlines, “entities who obtain equal to or above 80 points qualify for the Master Validator seal”. Based on our records, your security audit score was 72.5, which is below the 80-point requirement. As such, your group was not awarded the “Master Validator” badge.

**Comment by jamescowling** [comment]
Hi @bohan-zhang looks like you're using the scaled boost from the audit and not the audit points themselves. I received 90 points:

Screenshot 2020-06-26 12 09 55

**Comment by henry-zhang-bohan** [comment]
Hey @JamesCowling -- indeed you're right and I made a mistake. Sorry!

**Review by henry-zhang-bohan — APPROVED** [review]

**Comment by jamescowling** [comment]
Hi @bohan-zhang can we have someone land this so I don't have to keep fixing merge conflicts?

**Pull request merged**
