### PR TITLE
Use path.join() in metadata CLI requests to avoid // in URIs

### PR DESCRIPTION
**Pull request by lahabana**
### Description

If the metadataURL was registered with a trailling slash the verify attestation service calls would fail as it would build URIs with 2 "/".
This avoids this by using `path.join()`.

### CODE REVIEW

**Review by gastonponti — APPROVED** [review]
LGTM 👍 
Thanks!

**Comment by lahabana** [comment]
Rebased. #4313 Did fix this issue but it was introducing a function which I think is unecessary @nambrot might have a different opinion though

**Comment by jmrossy** [comment]
From the node documentation, it looks like the `path` package is meant for 'working with file and directory paths'.
Just did a quick test with it in a node repl and it seems like it mangles URLs:
```
> const path = require('path')
undefined
> path.join('http://google.com', 'hi')
'http:/google.com/hi'
```

@lahabana Are you sure path can be safely used for URL construction on all platforms?

**Review by jmrossy — CHANGES_REQUESTED** [review]
See comment above

**Comment by lahabana** [comment]
My bad then! Closing thanks for checking out

**Pull request closed without merging**
