### PR TITLE
fix(dkg): improve naming in the DKG

### PR DESCRIPTION
**Pull request by kobigurk**
.

### CODE REVIEW

**Review by codyborn — APPROVED** [review]
🙌

**Comment by aaronmgdr** [comment]
lgtm

**Comment by barbaraliau** [comment]
@kobigurk lgtm except for the merge conflict.

**Comment by eelanagaraj** [comment]
spoke with @kobigurk on this -- we will check in when he's back in office and double check that the merge conflict resolution looks good + if it makes sense to merge or close

**Review by kobigurk-clabs — APPROVED** [review]
LGTM!
In line with the changes in https://github.com/celo-org/celo-threshold-bls-rs/commit/56b4b05d9a234f57a610d98a15b18a010115cd9b

**Pull request merged**
