### PR TITLE
[Wallet] Change Simplex whitelist for blacklist

### LINKED ISSUE #5850: Change Simplex whitelist for blacklist
### Expected Behavior

Simplex is available by default in alll countries except those on a blacklist

### Current Behavior

Simplex is only available on the countries on a whitelist.

### PR DESCRIPTION
**Pull request by gnardini**
### Description

The title is pretty self-explanatory.

### Tested

Manually and there's a unit test.

### Related issues

- Fixes #5850

### CODE REVIEW

**Review by annakaz — APPROVED** [review]
👍

**Comment by Lss-Ankit** [comment]
Hi @gnardini just small clarification can you please let us know that which are whitelisted & black listed countries 
- We have verified with Philippines not able to see simplex page user redirecting to moonpay

**Comment by jeanregisser** [comment]
Hi Ankit Simplex is now disabled for the following countries: https://github.com/celo-org/celo-monorepo/blob/f60e1428c63f7af59771d7abe3d7b9078e72632a/packages/mobile/src/flags.ts#L46-L83
Countries not in that list are enabled.

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser thanks for giving countries which simplex is disable 
We have verified simplex with below countries 
**Countries disable simplex**
- AL : **Disable**
- PH : **Disable**
- ZW : **Disable**
- YE : **Disable**
- VE: **Disable**
- VU : **Disable**
- UG : **Disable**
- SO:  **Disable**
- WS : **Disable**
- PA : **Disable**

**Pull request merged**
