### PR TITLE
Add opengraph metadata

### LINKED ISSUE #2169: Add Open Graph data and images
Brandkit pages should use <OpenGraph /> component so they have nice previews on facebook and twitter and such.

will need Images 1500x1500 for the preview. 

decision: 1 preview per page or can we share between pages in brand kit?

Also missing images for 

/build/wallet
/build/faucet
and pages like terms and stake off terms / privacy

### PR DESCRIPTION
**Pull request by aaronmgdr**
### Description

Add full Open Graph meta data to brand Kit pages

add open graph  image to `/build/faucet` `/build/wallet` 

### Tested

confirmed the title and description, should test image shows correct once not on localhost

### Other changes

_Describe any minor or "drive-by" changes here._

### Related issues

- Fixes #2169

### CODE REVIEW

**Review by jmrossy — COMMENTED** [review]
Should we have these metadata tags on every page? If so, should they be added to the Page component?

**Comment by aaronmgdr** [comment]
> Should we have these metadata tags on every page? If so, should they be added to the Page component?

@jmrossy Im not clear on what you are asking/proposing. 

We do want each page in the brandkit and most other pages to have the metatags. They are mostly different per page, the brandkit pages do share a preview image however. 

note the <Page> component is only for brandkit experience pages.

**Comment by jmrossy** [comment]
> > Should we have these metadata tags on every page? If so, should they be added to the Page component?
> 
> @jmrossy Im not clear on what you are asking/proposing.
> 
> We do want each page in the brandkit and most other pages to have the metatags. They are mostly different per page, the brandkit pages do share a preview image however.
> 
> note the component is only for brandkit experience pages.

@aaronmgdr My thought was to have these be mandatory props of for each Page wrapper if we wanted them on every page. If we don't then nevermind :)

**Comment by jmrossy** [comment]
Assigning back as tests are failing

**Comment by aaronmgdr** [comment]
closing as @cmcewen included these changes in https://github.com/celo-org/celo-monorepo/pull/2279

**Pull request closed without merging**
