### PR TITLE
Nambrot/fix crawler

### PR DESCRIPTION
**Pull request by nambrot**
### Description

Makes some minor fixes so that the crawler can actually run. Already does so on RC1

### CODE REVIEW

**Review by annakaz — APPROVED** [review]
👍

**Review by jcortejoso — APPROVED** [review]
lgtm

**Comment by aaronmgdr** [comment]
automerge seems to have failed?

**Comment by barbaraliau** [comment]
@nambrot is this PR still relevant?

**Comment by barbaraliau** [comment]
Closing since there hasn't been any recent activity.

**Pull request closed without merging**
